services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ocP7api.norxciel.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=production"
    ports:
     - 80
    deploy:
      resources:
        limits:
          memory: 128M

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - API_URL=http://api/
    ports:
     - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ocP7demo.norxciel.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=production"