services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ocP7api.norxciel.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=production"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - API_URL=http://api/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ocP7demo.norxciel.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=production"