services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocp7api.rule=Host(`ocP7api.norxciel.fr`)"
      - "traefik.http.routers.ocp7api.entrypoints=websecure"
      - "traefik.http.routers.ocp7api.tls.certresolver=production"
    deploy:
      resources:
        limits:
          memory: 64M

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - API_URL=http://api/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocp7demo.rule=Host(`ocP7demo.norxciel.fr`)"
      - "traefik.http.routers.ocp7demo.entrypoints=websecure"
      - "traefik.http.routers.ocp7demo.tls.certresolver=production"