services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 127.0.0.1:8081:80

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 127.0.0.1:8082:80
    environment:
      - API_URL=http://api/