FROM python:3.11-slim

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt
RUN pip install -U setuptools pip
RUN pip install --no-cache-dir -r /api/requirements.txt

COPY ./src/utils/ /api/utils/
COPY ./src/models/ /api/models/
COPY ./src/api.py /api/api.py

EXPOSE 80

# CMD ["fastapi", "run", "--port", "80", "/api/api.py"]
CMD ["uvicorn", "fastapi:api", "--host", "0.0.0.0", "--port", "80"]