name: Application Tests
on:
  push:
      branches:
        - main
      paths:
        - '**/*.py'
        - '**/*pipeline.yml'
        - '**/Dockerfile.*'
        - 'compose*.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run API tests
        run: |
          python3 -m pytest -vW "ignore" -k api
      - name: Run utils tests
        run: |
          python3 -m pytest -vW "ignore" -k utils
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Create .ssh Directory
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Connect & Pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_OPTI }} "cd ${{ secrets.WORKDIR }} && git checkout main && git pull && docker compose up -d --build"
      - name: Cleanup
        run: |
          rm -rf ~/.ssh
          