name: Application Tests
on:
  push:
      paths:
        - '**/*.py'
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Tests"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run API tests
        run: |
          python3 -m pytest -vW "ignore" -k api
      - name: Run utils tests
        run: |
          python3 -m pytest -vW "ignore" -k utils
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts